Repository mingportal0/anygym, pull requests merged in 2020-11, with the labels that each got.

#19 MyDrawer 분리
  app/App.js
  app/components/Home.js
  app/components/cmn/DrawerNavigator.js
  package.json
Labels: todo

#25 [기구사용법 UI] 영상 리스트 수정 #17
  .expo/packager-info.json
  app/components/excerGuide/ExcerGuide.js
  app/components/excerGuide/SearchBar.js
  app/containers/ExcerGuideList.js
  package-lock.json
  package.json
  yarn.lock
Labels: development

#28 [공통] 햄버거 메뉴가 상단바에 가려지는 오류
  app/App.js
Labels: bug
